import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

export class PDFService {
  static async generateScorecard(data: {
    userName: string;
    testName: string;
    examName: string;
    score: number;
    totalMarks: number;
    percentage: number;
    rank: number;
    percentile: number;
    accuracy: number;
    timeTaken: number;
    date: Date;
    subjectPerformance?: any[];
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc  = new PDFDocument({ margin: 50, size: 'A4' });
      const pass = new PassThrough();
      const chunks: Buffer[] = [];

      pass.on('data',  chunk => chunks.push(chunk));
      pass.on('end',   () => resolve(Buffer.concat(chunks)));
      pass.on('error', reject);
      doc.pipe(pass);

      // Header
      doc.rect(0, 0, doc.page.width, 80).fill('#1a365d');
      doc.fillColor('white').fontSize(24).font('Helvetica-Bold')
        .text('PYQPB — Score Report', 50, 25, { align: 'center' });
      doc.fillColor('black').moveDown(2);

      // Candidate info
      doc.fontSize(14).font('Helvetica-Bold').text(data.userName);
      doc.fontSize(12).font('Helvetica').fillColor('#555')
        .text(`${data.testName} | ${data.examName}`)
        .text(`Date: ${new Date(data.date).toLocaleDateString('en-IN')}`)
        .moveDown();

      // Score box
      doc.rect(50, doc.y, 240, 80).fill('#EBF8FF').stroke('#3182CE');
      doc.fillColor('#1a365d').fontSize(36).font('Helvetica-Bold')
        .text(`${data.score}/${data.totalMarks}`, 60, doc.y - 70, { width: 220, align: 'center' });
      doc.fontSize(12).text(`${data.percentage.toFixed(1)}%`, 60, doc.y - 30, { width: 220, align: 'center' });

      // Rank box
      const rankX = 310;
      doc.rect(rankX, doc.y - 80, 240, 80).fill('#F0FFF4').stroke('#38A169');
      doc.fillColor('#276749').fontSize(36).font('Helvetica-Bold')
        .text(`#${data.rank}`, rankX + 10, doc.y - 80, { width: 220, align: 'center' });
      doc.fontSize(12).text(`${data.percentile.toFixed(1)} percentile`, rankX + 10, doc.y - 30, { width: 220, align: 'center' });

      doc.moveDown(2);

      // Stats row
      const stats = [
        ['Accuracy',    `${data.accuracy.toFixed(1)}%`],
        ['Time Taken',  `${Math.floor(data.timeTaken / 60)} min`],
        ['Percentile',  `${data.percentile.toFixed(1)}%`],
      ];
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#2D3748');
      stats.forEach(([label, value], i) => {
        const x = 50 + i * 170;
        doc.rect(x, doc.y, 160, 50).fill('#F7FAFC').stroke('#E2E8F0');
        doc.fillColor('#718096').text(label, x + 10, doc.y - 45, { width: 140, align: 'center' });
        doc.fillColor('#2D3748').fontSize(16).text(value, x + 10, doc.y - 25, { width: 140, align: 'center' });
        doc.fontSize(11);
      });

      doc.moveDown(3);

      // Subject performance table
      if (data.subjectPerformance?.length) {
        doc.fontSize(13).font('Helvetica-Bold').fillColor('#1a365d').text('Subject-wise Performance').moveDown(0.5);

        data.subjectPerformance.forEach((s: any) => {
          const accuracy = s.total > 0 ? ((s.correct / s.total) * 100).toFixed(1) : '0';
          doc.fontSize(10).font('Helvetica').fillColor('#4A5568')
            .text(`${s.subject}: ${s.correct}/${s.total} correct (${accuracy}% accuracy)`, { indent: 10 });
        });
      }

      // Footer
      doc.fontSize(8).fillColor('#999')
        .text('Generated by PYQPB — India\'s #1 Exam Preparation Platform', 50, doc.page.height - 40, { align: 'center' });

      doc.end();
    });
  }
}

export default PDFService;