import dotenv from 'dotenv';
dotenv.config();

import connectDB from '../../config/database.config';
import Exam from '../../models/Exam.model';
import logger from '../../utils/logger';

const examsData = [
  // ─── SSC ──────────────────────────────────────────────────────────────────
  {
    name: 'SSC Combined Graduate Level', shortName: 'SSC CGL', category: 'SSC',
    description: 'Combined Graduate Level Exam for Group B and C posts in Government ministries.',
    conductedBy: 'Staff Selection Commission', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 32, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 200, duration: 60, totalQuestions: 100, sections: [{ name: 'Tier I', subjects: ['General Intelligence', 'General Awareness', 'Quantitative Aptitude', 'English'], questionsCount: 100, marksPerQuestion: 2, negativeMarking: 0.5 }] },
    syllabus: ['Reasoning', 'General Knowledge', 'Mathematics', 'English Language'],
    officialWebsite: 'https://ssc.nic.in', isActive: true, isPremium: false, popularity: 1500,
    mockTestsAvailable: 50, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['SSC', 'Graduate Level', 'Central Government'], slug: 'ssc-combined-graduate-level',
  },
  {
    name: 'SSC Combined Higher Secondary Level', shortName: 'SSC CHSL', category: 'SSC',
    description: 'Exam for LDC, JSA, PA, SA posts in government departments.',
    conductedBy: 'Staff Selection Commission', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 27, qualification: '12th Pass' },
    examPattern: { totalMarks: 200, duration: 60, totalQuestions: 100, sections: [{ name: 'Tier I', subjects: ['English', 'GK', 'Quantitative Aptitude', 'Reasoning'], questionsCount: 100, marksPerQuestion: 2, negativeMarking: 0.5 }] },
    syllabus: ['English', 'General Knowledge', 'Quantitative Aptitude', 'Reasoning'],
    officialWebsite: 'https://ssc.nic.in', isActive: true, isPremium: false, popularity: 1200,
    mockTestsAvailable: 40, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['SSC', 'Higher Secondary', '12th Pass', 'LDC'], slug: 'ssc-combined-higher-secondary-level',
  },
  {
    name: 'SSC General Duty Constable', shortName: 'SSC GD', category: 'SSC',
    description: 'Recruitment for GD Constable in CAPFs, NIA, SSF and Rifleman in AR.',
    conductedBy: 'Staff Selection Commission', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 23, qualification: '10th Pass' },
    examPattern: { totalMarks: 160, duration: 60, totalQuestions: 80, sections: [{ name: 'CBT', subjects: ['English', 'GK', 'Mathematics', 'Reasoning'], questionsCount: 80, marksPerQuestion: 2, negativeMarking: 0.5 }] },
    syllabus: ['Elementary Mathematics', 'Reasoning', 'English', 'General Knowledge'],
    officialWebsite: 'https://ssc.nic.in', isActive: true, isPremium: false, popularity: 1100,
    mockTestsAvailable: 35, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['SSC', 'Constable', 'CAPF', '10th Pass'], slug: 'ssc-general-duty-constable',
  },
  {
    name: 'SSC Multi Tasking Staff', shortName: 'SSC MTS', category: 'SSC',
    description: 'Recruitment for Multi Tasking Non-Technical Staff in Central Government offices.',
    conductedBy: 'Staff Selection Commission', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 25, qualification: '10th Pass' },
    examPattern: { totalMarks: 150, duration: 90, totalQuestions: 100, sections: [{ name: 'Session I', subjects: ['Numerical Ability', 'Reasoning'], questionsCount: 40, marksPerQuestion: 3, negativeMarking: 1 }] },
    syllabus: ['Mathematics', 'Reasoning', 'English', 'General Awareness'],
    officialWebsite: 'https://ssc.nic.in', isActive: true, isPremium: false, popularity: 900,
    mockTestsAvailable: 30, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['SSC', 'MTS', '10th Pass'], slug: 'ssc-multi-tasking-staff',
  },
  {
    name: 'SSC Stenographer Grade C and D', shortName: 'SSC Steno', category: 'SSC',
    description: 'Recruitment for Stenographer Grade C & D in various central departments.',
    conductedBy: 'Staff Selection Commission', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 30, qualification: '12th Pass' },
    examPattern: { totalMarks: 200, duration: 120, totalQuestions: 200, sections: [{ name: 'Written', subjects: ['Reasoning', 'English', 'GK'], questionsCount: 200, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['General Intelligence & Reasoning', 'English Language & Comprehension', 'GK'],
    officialWebsite: 'https://ssc.nic.in', isActive: true, isPremium: false, popularity: 700,
    mockTestsAvailable: 20, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['SSC', 'Stenographer', '12th Pass', 'Typing'], slug: 'ssc-stenographer',
  },
  // ─── Railway ───────────────────────────────────────────────────────────────
  {
    name: 'Railway Non Technical Popular Category', shortName: 'RRB NTPC', category: 'Railway',
    description: 'Recruitment for Clerk, TA, CA, ASM, Goods Guard and other non-technical posts.',
    conductedBy: 'Railway Recruitment Board', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 33, qualification: "Bachelor's / 12th Pass" },
    examPattern: { totalMarks: 100, duration: 90, totalQuestions: 100, sections: [{ name: 'CBT 1', subjects: ['Mathematics', 'Reasoning', 'GK'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.33 }] },
    syllabus: ['Mathematics', 'Reasoning', 'General Awareness'],
    officialWebsite: 'https://indianrailways.gov.in', isActive: true, isPremium: false, popularity: 1400,
    mockTestsAvailable: 45, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['Railway', 'RRB', 'NTPC', 'Goods Guard'], slug: 'rrb-ntpc',
  },
  {
    name: 'Railway Group D', shortName: 'RRB Group D', category: 'Railway',
    description: 'Recruitment for Track Maintainer, Cabin Man, Gateman and Level 1 posts.',
    conductedBy: 'Railway Recruitment Board', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 33, qualification: '10th Pass + ITI' },
    examPattern: { totalMarks: 100, duration: 90, totalQuestions: 100, sections: [{ name: 'CBT', subjects: ['Mathematics', 'Reasoning', 'General Science', 'GK'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.33 }] },
    syllabus: ['Mathematics', 'Reasoning', 'General Science', 'GK'],
    officialWebsite: 'https://indianrailways.gov.in', isActive: true, isPremium: false, popularity: 1300,
    mockTestsAvailable: 40, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Railway', 'RRB', 'Group D', '10th Pass'], slug: 'rrb-group-d',
  },
  {
    name: 'Railway Junior Engineer', shortName: 'RRB JE', category: 'Railway',
    description: 'Recruitment for Junior Engineer in technical departments of Indian Railways.',
    conductedBy: 'Railway Recruitment Board', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 33, qualification: 'Diploma/BE/B.Tech' },
    examPattern: { totalMarks: 100, duration: 90, totalQuestions: 100, sections: [{ name: 'CBT 1', subjects: ['Mathematics', 'Physics', 'General Intelligence', 'GK'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.33 }] },
    syllabus: ['Mathematics', 'Physics', 'Reasoning', 'Engineering Basics'],
    officialWebsite: 'https://indianrailways.gov.in', isActive: true, isPremium: false, popularity: 800,
    mockTestsAvailable: 25, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Railway', 'RRB', 'JE', 'Technical', 'Diploma'], slug: 'rrb-junior-engineer',
  },
  {
    name: 'Railway Assistant Loco Pilot', shortName: 'RRB ALP', category: 'Railway',
    description: 'Recruitment for Assistant Loco Pilot and Technician posts in Indian Railways.',
    conductedBy: 'Railway Recruitment Board', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 28, qualification: '10th + ITI/Diploma' },
    examPattern: { totalMarks: 75, duration: 60, totalQuestions: 75, sections: [{ name: 'CBT 1', subjects: ['Mathematics', 'Physics', 'Reasoning', 'GK'], questionsCount: 75, marksPerQuestion: 1, negativeMarking: 0.33 }] },
    syllabus: ['Mathematics', 'Physics & Chemistry', 'Reasoning', 'GK'],
    officialWebsite: 'https://indianrailways.gov.in', isActive: true, isPremium: false, popularity: 950,
    mockTestsAvailable: 30, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Railway', 'RRB', 'ALP', 'Loco Pilot'], slug: 'rrb-assistant-loco-pilot',
  },
  // ─── Banking ───────────────────────────────────────────────────────────────
  {
    name: 'IBPS Probationary Officer', shortName: 'IBPS PO', category: 'Banking',
    description: 'Recruitment for Probationary Officer posts in public sector banks.',
    conductedBy: 'Institute of Banking Personnel Selection', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 20, maximumAge: 30, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 100, duration: 60, totalQuestions: 100, sections: [{ name: 'Prelims', subjects: ['English', 'Quantitative Aptitude', 'Reasoning'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning', 'Quantitative Aptitude', 'English', 'General Awareness', 'Computer'],
    officialWebsite: 'https://ibps.in', isActive: true, isPremium: false, popularity: 1350,
    mockTestsAvailable: 50, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['Banking', 'IBPS', 'PO', 'Bank'], slug: 'ibps-po',
  },
  {
    name: 'IBPS Clerk', shortName: 'IBPS Clerk', category: 'Banking',
    description: 'Recruitment for Clerical cadre posts in public sector banks.',
    conductedBy: 'Institute of Banking Personnel Selection', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 20, maximumAge: 28, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 100, duration: 60, totalQuestions: 100, sections: [{ name: 'Prelims', subjects: ['English', 'Numerical Ability', 'Reasoning'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning', 'Numerical Ability', 'English', 'GK', 'Computer'],
    officialWebsite: 'https://ibps.in', isActive: true, isPremium: false, popularity: 1200,
    mockTestsAvailable: 45, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['Banking', 'IBPS', 'Clerk', 'Bank'], slug: 'ibps-clerk',
  },
  {
    name: 'SBI Probationary Officer', shortName: 'SBI PO', category: 'Banking',
    description: 'One of the most prestigious banking exams for Probationary Officer posts in SBI.',
    conductedBy: 'State Bank of India', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 21, maximumAge: 30, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 100, duration: 60, totalQuestions: 100, sections: [{ name: 'Prelims', subjects: ['English', 'Quantitative Aptitude', 'Reasoning'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning', 'Quantitative Aptitude', 'English', 'Banking Awareness'],
    officialWebsite: 'https://sbi.co.in', isActive: true, isPremium: false, popularity: 1450,
    mockTestsAvailable: 55, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['Banking', 'SBI', 'PO', 'State Bank'], slug: 'sbi-po',
  },
  {
    name: 'SBI Clerk', shortName: 'SBI Clerk', category: 'Banking',
    description: 'SBI Junior Associates (Clerk) recruitment across SBI branches nationwide.',
    conductedBy: 'State Bank of India', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 20, maximumAge: 28, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 100, duration: 60, totalQuestions: 100, sections: [{ name: 'Prelims', subjects: ['English', 'Numerical Ability', 'Reasoning'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning', 'Numerical Ability', 'English', 'General Awareness'],
    officialWebsite: 'https://sbi.co.in', isActive: true, isPremium: false, popularity: 1100,
    mockTestsAvailable: 40, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['Banking', 'SBI', 'Clerk', 'State Bank'], slug: 'sbi-clerk',
  },
  {
    name: 'IBPS RRB Officer Scale I', shortName: 'IBPS RRB PO', category: 'Banking',
    description: 'Recruitment for Officer Scale I posts in Regional Rural Banks.',
    conductedBy: 'Institute of Banking Personnel Selection', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 30, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 80, duration: 45, totalQuestions: 80, sections: [{ name: 'Prelims', subjects: ['Reasoning', 'Quantitative Aptitude'], questionsCount: 80, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning', 'Quantitative Aptitude', 'English/Hindi', 'GK', 'Computer'],
    officialWebsite: 'https://ibps.in', isActive: true, isPremium: false, popularity: 800,
    mockTestsAvailable: 30, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Banking', 'IBPS', 'RRB', 'Rural Bank'], slug: 'ibps-rrb-po',
  },
  {
    name: 'IBPS RRB Office Assistant', shortName: 'IBPS RRB Clerk', category: 'Banking',
    description: 'Recruitment for Office Assistant (Multipurpose) in Regional Rural Banks.',
    conductedBy: 'Institute of Banking Personnel Selection', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 28, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 80, duration: 45, totalQuestions: 80, sections: [{ name: 'Prelims', subjects: ['Reasoning', 'Numerical Ability'], questionsCount: 80, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning', 'Numerical Ability', 'English/Hindi', 'GK', 'Computer'],
    officialWebsite: 'https://ibps.in', isActive: true, isPremium: false, popularity: 700,
    mockTestsAvailable: 25, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Banking', 'IBPS', 'RRB', 'Office Assistant'], slug: 'ibps-rrb-clerk',
  },
  // ─── UPSC ──────────────────────────────────────────────────────────────────
  {
    name: 'UPSC Civil Services Examination', shortName: 'UPSC CSE', category: 'UPSC',
    description: 'Most prestigious exam in India for IAS, IPS, IFS and All India Services.',
    conductedBy: 'Union Public Service Commission', examLevel: 'national', examMode: 'offline', frequency: 'yearly',
    eligibility: { minimumAge: 21, maximumAge: 32, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 2025, duration: 120, totalQuestions: 100, sections: [{ name: 'Prelims GS I', subjects: ['History', 'Geography', 'Polity', 'Economy', 'Science', 'Current Affairs'], questionsCount: 100, marksPerQuestion: 2, negativeMarking: 0.67 }] },
    syllabus: ['History', 'Geography', 'Polity', 'Economy', 'Environment', 'Science', 'Current Affairs', 'CSAT'],
    officialWebsite: 'https://upsc.gov.in', isActive: true, isPremium: true, popularity: 2000,
    mockTestsAvailable: 100, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020, 2019, 2018],
    tags: ['UPSC', 'IAS', 'IPS', 'Civil Services', 'All India Services'], slug: 'upsc-civil-services',
  },
  {
    name: 'UPSC Central Armed Police Forces', shortName: 'UPSC CAPF', category: 'UPSC',
    description: 'Recruitment for Assistant Commandant in BSF, CRPF, CISF, ITBP, SSB.',
    conductedBy: 'Union Public Service Commission', examLevel: 'national', examMode: 'offline', frequency: 'yearly',
    eligibility: { minimumAge: 20, maximumAge: 25, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 450, duration: 120, totalQuestions: 125, sections: [{ name: 'Paper I', subjects: ['GK', 'GS', 'Reasoning', 'English'], questionsCount: 125, marksPerQuestion: 2, negativeMarking: 0.67 }] },
    syllabus: ['GK & GS', 'English', 'Maths', 'Reasoning'],
    officialWebsite: 'https://upsc.gov.in', isActive: true, isPremium: false, popularity: 700,
    mockTestsAvailable: 20, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['UPSC', 'CAPF', 'BSF', 'CRPF', 'Commandant'], slug: 'upsc-capf',
  },
  // ─── Defence ───────────────────────────────────────────────────────────────
  {
    name: 'National Defence Academy', shortName: 'NDA', category: 'Defence',
    description: 'Entrance for Army, Navy and Air Force wings of NDA for 12th pass students.',
    conductedBy: 'Union Public Service Commission', examLevel: 'national', examMode: 'offline', frequency: 'half-yearly',
    eligibility: { minimumAge: 16, maximumAge: 19, qualification: '12th Pass (PCM for Air Force/Navy)' },
    examPattern: { totalMarks: 900, duration: 150, totalQuestions: 270, sections: [{ name: 'Maths', subjects: ['Mathematics'], questionsCount: 120, marksPerQuestion: 2.5, negativeMarking: 0.83 }] },
    syllabus: ['Mathematics', 'English', 'Physics', 'Chemistry', 'History', 'Geography', 'GK'],
    officialWebsite: 'https://upsc.gov.in', isActive: true, isPremium: false, popularity: 900,
    mockTestsAvailable: 30, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['Defence', 'NDA', 'Army', 'Navy', 'Air Force'], slug: 'nda',
  },
  {
    name: 'Combined Defence Services', shortName: 'CDS', category: 'Defence',
    description: 'Recruitment for IMA, Naval Academy, Air Force Academy and OTA.',
    conductedBy: 'Union Public Service Commission', examLevel: 'national', examMode: 'offline', frequency: 'half-yearly',
    eligibility: { minimumAge: 19, maximumAge: 25, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 300, duration: 120, totalQuestions: 300, sections: [{ name: 'English', subjects: ['English'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.33 }] },
    syllabus: ['English', 'General Knowledge', 'Elementary Mathematics'],
    officialWebsite: 'https://upsc.gov.in', isActive: true, isPremium: false, popularity: 750,
    mockTestsAvailable: 25, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['Defence', 'CDS', 'IMA', 'Air Force', 'Navy'], slug: 'cds',
  },
  {
    name: 'Agniveer Army', shortName: 'Agniveer', category: 'Defence',
    description: 'Short-term recruitment for soldiers in Indian Army under the Agnipath scheme.',
    conductedBy: 'Indian Army', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 17, maximumAge: 23, qualification: '10th/12th Pass' },
    examPattern: { totalMarks: 100, duration: 60, totalQuestions: 50, sections: [{ name: 'Written', subjects: ['GK', 'GS', 'Maths', 'English'], questionsCount: 50, marksPerQuestion: 2, negativeMarking: 0.5 }] },
    syllabus: ['GK', 'General Science', 'Mathematics', 'English'],
    officialWebsite: 'https://joinindianarmy.nic.in', isActive: true, isPremium: false, popularity: 850,
    mockTestsAvailable: 20, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Defence', 'Agniveer', 'Army', 'Agnipath'], slug: 'agniveer-army',
  },
  {
    name: 'Indian Coast Guard Navik', shortName: 'ICG Navik', category: 'Defence',
    description: 'Recruitment for Navik (GD) and Navik (DB) in Indian Coast Guard.',
    conductedBy: 'Indian Coast Guard', examLevel: 'national', examMode: 'online', frequency: 'quarterly',
    eligibility: { minimumAge: 18, maximumAge: 22, qualification: '12th Pass with PCM' },
    examPattern: { totalMarks: 100, duration: 60, totalQuestions: 100, sections: [{ name: 'Written', subjects: ['Maths', 'Physics', 'English', 'Reasoning', 'GK'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Mathematics', 'Physics', 'English', 'Reasoning', 'GK'],
    officialWebsite: 'https://joinindiancoastguard.cdac.in', isActive: true, isPremium: false, popularity: 500,
    mockTestsAvailable: 15, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Defence', 'Coast Guard', 'Navy', 'Navik'], slug: 'indian-coast-guard-navik',
  },
  // ─── Teaching ──────────────────────────────────────────────────────────────
  {
    name: 'Central Teacher Eligibility Test', shortName: 'CTET', category: 'Teaching',
    description: 'Eligibility test for teaching at Primary and Upper Primary level in Central Government schools.',
    conductedBy: 'Central Board of Secondary Education', examLevel: 'national', examMode: 'online', frequency: 'half-yearly',
    eligibility: { minimumAge: 18, qualification: 'D.El.Ed or B.Ed' },
    examPattern: { totalMarks: 150, duration: 150, totalQuestions: 150, sections: [{ name: 'Paper I', subjects: ['Child Development', 'Language I', 'Language II', 'Mathematics', 'EVS'], questionsCount: 150, marksPerQuestion: 1, negativeMarking: 0 }] },
    syllabus: ['Child Development & Pedagogy', 'Language I', 'Language II', 'Mathematics', 'EVS'],
    officialWebsite: 'https://ctet.nic.in', isActive: true, isPremium: false, popularity: 950,
    mockTestsAvailable: 30, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['Teaching', 'CTET', 'Teacher', 'Primary', 'CBSE'], slug: 'ctet',
  },
  {
    name: 'KVS Primary Teacher', shortName: 'KVS PRT', category: 'Teaching',
    description: 'Recruitment for Primary Teacher posts in Kendriya Vidyalayas.',
    conductedBy: 'Kendriya Vidyalaya Sangathan', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, qualification: '12th + D.El.Ed + CTET' },
    examPattern: { totalMarks: 180, duration: 180, totalQuestions: 180, sections: [{ name: 'Written', subjects: ['GK', 'Reasoning', 'English', 'Hindi', 'Pedagogy'], questionsCount: 180, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['GK & Current Affairs', 'Reasoning', 'English', 'Hindi', 'Pedagogy'],
    officialWebsite: 'https://kvsangathan.nic.in', isActive: true, isPremium: false, popularity: 600,
    mockTestsAvailable: 20, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Teaching', 'KVS', 'Kendriya Vidyalaya', 'PRT'], slug: 'kvs-prt',
  },
  {
    name: 'NVS TGT PGT Recruitment', shortName: 'NVS TGT', category: 'Teaching',
    description: 'Recruitment for Trained Graduate Teachers and PGTs in Navodaya Vidyalayas.',
    conductedBy: 'Navodaya Vidyalaya Samiti', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, qualification: "Bachelor's Degree + B.Ed + CTET" },
    examPattern: { totalMarks: 150, duration: 150, totalQuestions: 150, sections: [{ name: 'Written', subjects: ['Subject Knowledge', 'Reasoning', 'GK', 'Teaching'], questionsCount: 150, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Subject Knowledge', 'Reasoning', 'Teaching Aptitude', 'English', 'GK'],
    officialWebsite: 'https://navodaya.gov.in', isActive: true, isPremium: false, popularity: 500,
    mockTestsAvailable: 15, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Teaching', 'NVS', 'Navodaya', 'TGT', 'PGT'], slug: 'nvs-tgt-pgt',
  },
  // ─── Police ────────────────────────────────────────────────────────────────
  {
    name: 'Delhi Police Constable', shortName: 'Delhi Police', category: 'Police',
    description: 'Recruitment for Constable posts in Delhi Police force.',
    conductedBy: 'Staff Selection Commission', examLevel: 'state', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 25, qualification: '12th Pass' },
    examPattern: { totalMarks: 100, duration: 90, totalQuestions: 100, sections: [{ name: 'CBT', subjects: ['Reasoning', 'GK', 'Numerical Ability', 'Computer & English'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning', 'GK', 'Numerical Ability', 'Computer', 'English'],
    officialWebsite: 'https://delhipolice.nic.in', isActive: true, isPremium: false, popularity: 700,
    mockTestsAvailable: 25, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['Police', 'Delhi Police', 'Constable', 'SSC'], slug: 'delhi-police-constable',
  },
  {
    name: 'CISF Constable Tradesmen', shortName: 'CISF Constable', category: 'Police',
    description: 'Recruitment for Constable Tradesmen posts in Central Industrial Security Force.',
    conductedBy: 'Central Industrial Security Force', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 23, qualification: '10th Pass' },
    examPattern: { totalMarks: 100, duration: 60, totalQuestions: 100, sections: [{ name: 'Written', subjects: ['GK', 'Mathematics', 'Reasoning', 'English/Hindi'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['GK', 'Mathematics', 'Reasoning', 'English/Hindi'],
    officialWebsite: 'https://cisf.gov.in', isActive: true, isPremium: false, popularity: 500,
    mockTestsAvailable: 15, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Police', 'CISF', 'Constable', 'Paramilitary'], slug: 'cisf-constable',
  },
  {
    name: 'UP Police Constable', shortName: 'UP Police', category: 'Police',
    description: 'Recruitment for Constable posts in Uttar Pradesh Police.',
    conductedBy: 'Uttar Pradesh Police Recruitment Board', examLevel: 'state', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 22, qualification: '12th Pass' },
    examPattern: { totalMarks: 300, duration: 120, totalQuestions: 150, sections: [{ name: 'Written', subjects: ['GK', 'Hindi', 'Numerical Ability', 'Mental Aptitude'], questionsCount: 150, marksPerQuestion: 2, negativeMarking: 0.5 }] },
    syllabus: ['General Hindi', 'GK/Current Affairs', 'Numerical Ability', 'Mental Aptitude'],
    officialWebsite: 'https://uppbpb.gov.in', isActive: true, isPremium: false, popularity: 800,
    mockTestsAvailable: 25, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['Police', 'UP Police', 'Constable', 'Uttar Pradesh'], slug: 'up-police-constable',
  },
  // ─── Engineering ───────────────────────────────────────────────────────────
  {
    name: 'JEE Main', shortName: 'JEE Main', category: 'Engineering',
    description: 'Gateway to NITs, IIITs, CFTIs and qualifier for JEE Advanced. Largest engineering entrance.',
    conductedBy: 'National Testing Agency', examLevel: 'national', examMode: 'online', frequency: 'quarterly',
    eligibility: { minimumAge: 17, qualification: '12th Pass with PCM' },
    examPattern: { totalMarks: 300, duration: 180, totalQuestions: 90, sections: [{ name: 'B.E./B.Tech', subjects: ['Physics', 'Chemistry', 'Mathematics'], questionsCount: 90, marksPerQuestion: 4, negativeMarking: 1 }] },
    syllabus: ['Physics', 'Chemistry', 'Mathematics'],
    officialWebsite: 'https://jeemain.nta.ac.in', isActive: true, isPremium: false, popularity: 2000,
    mockTestsAvailable: 80, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020, 2019, 2018],
    tags: ['Engineering', 'JEE', 'Main', 'NIT', 'IIIT', 'PCM'], slug: 'jee-main',
  },
  {
    name: 'JEE Advanced', shortName: 'JEE Advanced', category: 'Engineering',
    description: 'Entrance exam for admission to IITs – most prestigious engineering colleges in India.',
    conductedBy: 'IIT (Rotating)', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 17, qualification: '12th Pass PCM 75%+', otherCriteria: 'Must qualify JEE Main Top 2.5L' },
    examPattern: { totalMarks: 360, duration: 180, totalQuestions: 54, sections: [{ name: 'Paper 1', subjects: ['Physics', 'Chemistry', 'Mathematics'], questionsCount: 54, marksPerQuestion: 4, negativeMarking: 1 }] },
    syllabus: ['Physics', 'Chemistry', 'Mathematics'],
    officialWebsite: 'https://jeeadv.ac.in', isActive: true, isPremium: true, popularity: 1800,
    mockTestsAvailable: 60, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020, 2019],
    tags: ['Engineering', 'IIT', 'JEE Advanced', 'PCM'], slug: 'jee-advanced',
  },
  {
    name: 'Graduate Aptitude Test in Engineering', shortName: 'GATE', category: 'Engineering',
    description: 'National exam for M.Tech/Ph.D admission and PSU recruitment.',
    conductedBy: 'IIT (Rotating)', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, qualification: "Bachelor's in Engineering/Science" },
    examPattern: { totalMarks: 100, duration: 180, totalQuestions: 65, sections: [{ name: 'Paper', subjects: ['General Aptitude', 'Technical Subject'], questionsCount: 65, marksPerQuestion: 1, negativeMarking: 0.33 }] },
    syllabus: ['General Aptitude', 'Engineering Mathematics', 'Technical Subject'],
    officialWebsite: 'https://gate.iitb.ac.in', isActive: true, isPremium: true, popularity: 1000,
    mockTestsAvailable: 40, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['Engineering', 'GATE', 'M.Tech', 'PSU', 'Research'], slug: 'gate',
  },
  // ─── Medical ───────────────────────────────────────────────────────────────
  {
    name: 'NEET Undergraduate', shortName: 'NEET UG', category: 'Medical',
    description: 'Single national entrance for MBBS, BDS, BAMS, BSMS, BUMS, BHMS courses.',
    conductedBy: 'National Testing Agency', examLevel: 'national', examMode: 'offline', frequency: 'yearly',
    eligibility: { minimumAge: 17, qualification: '12th Pass with PCB 50%+' },
    examPattern: { totalMarks: 720, duration: 200, totalQuestions: 200, sections: [{ name: 'NEET UG', subjects: ['Physics', 'Chemistry', 'Botany', 'Zoology'], questionsCount: 200, marksPerQuestion: 4, negativeMarking: 1 }] },
    syllabus: ['Physics', 'Chemistry', 'Biology (Botany + Zoology)'],
    officialWebsite: 'https://neet.nta.nic.in', isActive: true, isPremium: true, popularity: 2200,
    mockTestsAvailable: 100, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020, 2019, 2018],
    tags: ['Medical', 'NEET', 'MBBS', 'BDS', 'PCB', 'NTA'], slug: 'neet-ug',
  },
  {
    name: 'AIIMS PG Entrance', shortName: 'AIIMS PG', category: 'Medical',
    description: 'Entrance exam for PG Medical courses at AIIMS institutions.',
    conductedBy: 'AIIMS New Delhi', examLevel: 'national', examMode: 'online', frequency: 'half-yearly',
    eligibility: { minimumAge: 18, qualification: 'MBBS Degree' },
    examPattern: { totalMarks: 200, duration: 180, totalQuestions: 200, sections: [{ name: 'Written', subjects: ['Pre-Clinical', 'Para-Clinical', 'Clinical'], questionsCount: 200, marksPerQuestion: 1, negativeMarking: 0.33 }] },
    syllabus: ['Pre-Clinical Subjects', 'Para-Clinical Subjects', 'Clinical Subjects'],
    officialWebsite: 'https://aiims.edu', isActive: true, isPremium: true, popularity: 600,
    mockTestsAvailable: 20, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Medical', 'AIIMS', 'PG', 'Postgraduate', 'MBBS'], slug: 'aiims-pg',
  },
  // ─── State PSC ─────────────────────────────────────────────────────────────
  {
    name: 'BPSC Combined Competitive Exam', shortName: 'BPSC CCE', category: 'State PSC',
    description: 'Bihar Public Service Commission exam for state government posts.',
    conductedBy: 'Bihar Public Service Commission', examLevel: 'state', examMode: 'offline', frequency: 'yearly',
    eligibility: { minimumAge: 20, maximumAge: 37, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 150, duration: 120, totalQuestions: 150, sections: [{ name: 'Prelims', subjects: ['General Studies'], questionsCount: 150, marksPerQuestion: 1, negativeMarking: 0 }] },
    syllabus: ['GK & Current Affairs', 'History', 'Geography', 'Economy', 'Polity', 'Science'],
    officialWebsite: 'https://bpsc.bih.nic.in', isActive: true, isPremium: false, popularity: 700,
    mockTestsAvailable: 25, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['State PSC', 'BPSC', 'Bihar', 'State Government'], slug: 'bpsc-cce',
  },
  {
    name: 'UPPSC PCS Preliminary', shortName: 'UPPSC PCS', category: 'State PSC',
    description: 'Uttar Pradesh Public Service Commission Provincial Civil Services exam.',
    conductedBy: 'Uttar Pradesh Public Service Commission', examLevel: 'state', examMode: 'offline', frequency: 'yearly',
    eligibility: { minimumAge: 21, maximumAge: 40, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 200, duration: 120, totalQuestions: 150, sections: [{ name: 'Paper 1', subjects: ['GS'], questionsCount: 150, marksPerQuestion: 2, negativeMarking: 0.5 }] },
    syllabus: ['History', 'Geography', 'Polity', 'Economy', 'Science', 'Current Events'],
    officialWebsite: 'https://uppsc.up.nic.in', isActive: true, isPremium: false, popularity: 800,
    mockTestsAvailable: 30, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['State PSC', 'UPPSC', 'Uttar Pradesh', 'PCS'], slug: 'uppsc-pcs',
  },
  {
    name: 'MPSC State Service Exam', shortName: 'MPSC', category: 'State PSC',
    description: 'Maharashtra Public Service Commission exam for Group A and B posts.',
    conductedBy: 'Maharashtra Public Service Commission', examLevel: 'state', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 19, maximumAge: 38, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 200, duration: 120, totalQuestions: 100, sections: [{ name: 'Prelims Paper I', subjects: ['GS', 'CSAT'], questionsCount: 100, marksPerQuestion: 2, negativeMarking: 0 }] },
    syllabus: ['History', 'Geography', 'Polity', 'Economy', 'Science', 'Maharashtra Specific GK'],
    officialWebsite: 'https://mpsc.gov.in', isActive: true, isPremium: false, popularity: 600,
    mockTestsAvailable: 20, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['State PSC', 'MPSC', 'Maharashtra', 'State Government'], slug: 'mpsc-state-service',
  },
  {
    name: 'RPSC RAS Exam', shortName: 'RPSC RAS', category: 'State PSC',
    description: 'Rajasthan Administrative Service exam for Group A state services.',
    conductedBy: 'Rajasthan Public Service Commission', examLevel: 'state', examMode: 'offline', frequency: 'yearly',
    eligibility: { minimumAge: 21, maximumAge: 40, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 200, duration: 180, totalQuestions: 150, sections: [{ name: 'Prelims', subjects: ['GS & GK'], questionsCount: 150, marksPerQuestion: 2, negativeMarking: 0.33 }] },
    syllabus: ['History & Culture', 'Geography', 'Indian Polity', 'Economy', 'Science', 'Rajasthan GK'],
    officialWebsite: 'https://rpsc.rajasthan.gov.in', isActive: true, isPremium: false, popularity: 550,
    mockTestsAvailable: 18, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['State PSC', 'RPSC', 'RAS', 'Rajasthan'], slug: 'rpsc-ras',
  },
  // ─── MBA ───────────────────────────────────────────────────────────────────
  {
    name: 'Common Admission Test', shortName: 'CAT', category: 'MBA',
    description: 'Gateway to IIMs and top B-schools. Most prestigious MBA entrance in India.',
    conductedBy: 'IIM (Rotating)', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, qualification: "Bachelor's Degree 50%+" },
    examPattern: { totalMarks: 198, duration: 120, totalQuestions: 66, sections: [{ name: 'VARC', subjects: ['Verbal Ability', 'Reading Comprehension'], questionsCount: 24, marksPerQuestion: 3, negativeMarking: 1 }] },
    syllabus: ['VARC', 'DILR', 'Quantitative Aptitude'],
    officialWebsite: 'https://iimcat.ac.in', isActive: true, isPremium: true, popularity: 1200,
    mockTestsAvailable: 40, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['MBA', 'CAT', 'IIM', 'Management', 'VARC', 'QA'], slug: 'cat',
  },
  {
    name: 'Xavier Aptitude Test', shortName: 'XAT', category: 'MBA',
    description: 'National level MBA entrance exam for admission to XLRI and 150+ B-schools.',
    conductedBy: 'Xavier Labour Relations Institute', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 105, duration: 190, totalQuestions: 101, sections: [{ name: 'Part 1', subjects: ['Verbal & Logical Ability', 'Decision Making', 'Quantitative Ability & DI'], questionsCount: 75, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Verbal & Logical Ability', 'Decision Making', 'Quantitative Ability', 'GK'],
    officialWebsite: 'https://xatonline.in', isActive: true, isPremium: false, popularity: 700,
    mockTestsAvailable: 20, pyqYearsAvailable: [2024, 2023, 2022, 2021],
    tags: ['MBA', 'XAT', 'XLRI', 'Management'], slug: 'xat',
  },
  // ─── Law ───────────────────────────────────────────────────────────────────
  {
    name: 'Common Law Admission Test', shortName: 'CLAT', category: 'Law',
    description: 'Centralized entrance for UG and PG law programs in National Law Universities.',
    conductedBy: 'Consortium of National Law Universities', examLevel: 'national', examMode: 'offline', frequency: 'yearly',
    eligibility: { minimumAge: 17, qualification: '12th Pass 45%+' },
    examPattern: { totalMarks: 120, duration: 120, totalQuestions: 120, sections: [{ name: 'UG', subjects: ['English', 'Current Affairs & GK', 'Legal Reasoning', 'Logical Reasoning', 'Quantitative Techniques'], questionsCount: 120, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['English', 'Current Affairs', 'Legal Reasoning', 'Logical Reasoning', 'Quantitative Techniques'],
    officialWebsite: 'https://consortiumofnlus.ac.in', isActive: true, isPremium: false, popularity: 700,
    mockTestsAvailable: 25, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['Law', 'CLAT', 'NLU', 'LLB', 'Legal'], slug: 'clat',
  },
  {
    name: 'All India Bar Examination', shortName: 'AIBE', category: 'Law',
    description: 'Eligibility test for law graduates to practice as advocates in India.',
    conductedBy: 'Bar Council of India', examLevel: 'national', examMode: 'offline', frequency: 'half-yearly',
    eligibility: { minimumAge: 18, qualification: 'LLB / BA LLB Degree' },
    examPattern: { totalMarks: 100, duration: 210, totalQuestions: 100, sections: [{ name: 'Written', subjects: ['Constitutional Law', 'IPC', 'CPC', 'Evidence', 'Professional Ethics'], questionsCount: 100, marksPerQuestion: 1, negativeMarking: 0 }] },
    syllabus: ['Constitutional Law', 'IPC', 'CrPC', 'CPC', 'Evidence Act', 'Professional Ethics'],
    officialWebsite: 'https://barcouncilofindia.org', isActive: true, isPremium: false, popularity: 400,
    mockTestsAvailable: 10, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Law', 'AIBE', 'Bar Exam', 'Advocate', 'LLB'], slug: 'aibe',
  },
  // ─── University ────────────────────────────────────────────────────────────
  {
    name: 'University Grants Commission NET', shortName: 'UGC NET', category: 'University',
    description: 'Eligibility test for Junior Research Fellowship and Assistant Professor posts.',
    conductedBy: 'National Testing Agency', examLevel: 'national', examMode: 'online', frequency: 'half-yearly',
    eligibility: { minimumAge: 18, qualification: "Master's Degree 55%+" },
    examPattern: { totalMarks: 300, duration: 180, totalQuestions: 150, sections: [{ name: 'Paper I', subjects: ['Teaching & Research Aptitude'], questionsCount: 50, marksPerQuestion: 2, negativeMarking: 0 }] },
    syllabus: ['Teaching Aptitude', 'Research Aptitude', 'Comprehension', 'Communication', 'Subject Paper'],
    officialWebsite: 'https://ugcnet.nta.nic.in', isActive: true, isPremium: true, popularity: 900,
    mockTestsAvailable: 35, pyqYearsAvailable: [2024, 2023, 2022, 2021, 2020],
    tags: ['University', 'UGC NET', 'JRF', 'Assistant Professor', 'Research'], slug: 'ugc-net',
  },
  {
    name: 'CUET Undergraduate', shortName: 'CUET UG', category: 'University',
    description: 'Common University Entrance Test for admission to UG programs in central universities.',
    conductedBy: 'National Testing Agency', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 16, qualification: '12th Pass' },
    examPattern: { totalMarks: 800, duration: 60, totalQuestions: 50, sections: [{ name: 'Domain Subject', subjects: ['Subject Specific'], questionsCount: 50, marksPerQuestion: 5, negativeMarking: 1 }] },
    syllabus: ['Language', 'Domain Subjects', 'General Test'],
    officialWebsite: 'https://cuet.samarth.ac.in', isActive: true, isPremium: false, popularity: 1000,
    mockTestsAvailable: 30, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['University', 'CUET', 'Central University', 'UG Admission'], slug: 'cuet-ug',
  },
  // ─── Other ─────────────────────────────────────────────────────────────────
  {
    name: 'LIC Assistant Administrative Officer', shortName: 'LIC AAO', category: 'Other',
    description: 'Recruitment for AAO posts in Life Insurance Corporation of India.',
    conductedBy: 'Life Insurance Corporation of India', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 21, maximumAge: 30, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 300, duration: 120, totalQuestions: 160, sections: [{ name: 'Prelims', subjects: ['Reasoning', 'Quantitative Aptitude', 'English'], questionsCount: 105, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning Ability', 'Quantitative Aptitude', 'English Language', 'GK', 'Insurance & Financial Markets'],
    officialWebsite: 'https://licindia.in', isActive: true, isPremium: false, popularity: 600,
    mockTestsAvailable: 20, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Insurance', 'LIC', 'AAO', 'Finance'], slug: 'lic-aao',
  },
  {
    name: 'NABARD Grade A', shortName: 'NABARD A', category: 'Other',
    description: 'Recruitment for Grade A (Assistant Manager) in NABARD.',
    conductedBy: 'National Bank for Agriculture and Rural Development', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 21, maximumAge: 30, qualification: "Bachelor's Degree 60%+" },
    examPattern: { totalMarks: 200, duration: 120, totalQuestions: 200, sections: [{ name: 'Phase I', subjects: ['Reasoning', 'English', 'Computer', 'GK', 'Economic & Social Issues', 'Agriculture'], questionsCount: 200, marksPerQuestion: 1, negativeMarking: 0.25 }] },
    syllabus: ['Reasoning', 'English', 'Computer', 'GK', 'Economic Issues', 'Agriculture & Rural Development'],
    officialWebsite: 'https://nabard.org', isActive: true, isPremium: false, popularity: 450,
    mockTestsAvailable: 15, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Banking', 'NABARD', 'Agriculture', 'Grade A'], slug: 'nabard-grade-a',
  },
  {
    name: 'Food Corporation of India Management Trainee', shortName: 'FCI MT', category: 'Other',
    description: 'Recruitment for Management Trainee posts in Food Corporation of India.',
    conductedBy: 'Food Corporation of India', examLevel: 'national', examMode: 'online', frequency: 'yearly',
    eligibility: { minimumAge: 18, maximumAge: 28, qualification: "Bachelor's Degree" },
    examPattern: { totalMarks: 300, duration: 120, totalQuestions: 120, sections: [{ name: 'Phase I', subjects: ['Reasoning', 'English', 'Numerical Aptitude', 'GK'], questionsCount: 120, marksPerQuestion: 1, negativeMarking: 0 }] },
    syllabus: ['Reasoning Ability', 'English', 'Numerical Aptitude', 'GK & Current Affairs'],
    officialWebsite: 'https://fci.gov.in', isActive: true, isPremium: false, popularity: 500,
    mockTestsAvailable: 15, pyqYearsAvailable: [2024, 2023, 2022],
    tags: ['Government', 'FCI', 'Management Trainee', 'Food Corporation'], slug: 'fci-mt',
  },
];

const seedExams = async () => {
  try {
    await connectDB();

    const existingCount = await Exam.countDocuments();
    if (existingCount > 0) {
      logger.info(`Skipping — ${existingCount} exams already exist. Use --force to override.`);
      process.exit(0);
    }

    const created = await Exam.insertMany(examsData);
    logger.info(`✅ ${created.length} exams seeded successfully!`);
    process.exit(0);
  } catch (error: any) {
    logger.error(`Error seeding exams: ${error.message}`);
    process.exit(1);
  }
};

seedExams();